sudo: required

environment:
  - RELEASE_VERSION=
services:
  - docker

before_install:
  - RELEASE_VERSION=`cat release_version.txt`

install:
  - docker-compose -f docker-compose.travis.yml build

before_script:
  - docker tag rezme/resume-token-api:latest rezme/resume-token-api:$RELEASE_VERSION

script:
  - docker login --username $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD
  - docker push rezme/resume-token-api:latest
  - docker push rezme/resume-token-api:$RELEASE_VERSION

after_script:
  - docker pull rezme/resume-token-api:latest
  - docker pull rezme/resume-token-api:$RELEASE_VERSION
