version: "3"
services:
  api:
    image: rezme/resume-token-api
    build:
      context: .
    ports:
      - 80:80
    env_file: .env
    volumes:
      - ./resources:/opt/app/resources
      - ./schemas:/opt/app/schemas
      - ./index.js:/opt/app/index.js
      - ./package.json:/opt/app/package.json
